### ISSUE TITLE
Nil value causes crash at startup

### ISSUE THREAD

**Issue by Athozus** [Andrey2470T/circular_saw_ext#2]
I get this error when I launch the server : 
```lua
init.lua:117: attempt to index field 'defs' (a nil value)
```

This test server is created for a long time (only on singleplayer), and I used moreblocks since its debut.

**Comment by Andrey2470T** [comment]
Did you do any changes in the original moreblocks? And do you use its the latest versions (it's very recommended)? Also, I've made a fix in the mod allowing to show all registered microblocks, not only an upper half of them.

**Comment by Athozus** [comment]
Yes, I was used a 3-year-old version :grin: Thanks for the fix anyway :)

**Comment by Athozus** [comment]
Yes, I was used a 3-year-old version :grin: Thanks for the fix anyway :)
